// <auto-generated>
//   Generated by axial schemagen from category.contract (Category.v1).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Axial.Tests.Generated

open Axial.Validation
open Axial.Schema

/// A recursive category tree used to prove self-references in generated schemas.
type Category =
    {
        /// Stable display name.
        Name: string
        /// Child categories use the same wire contract.
        Children: Category list
    }

/// Schema and boundary functions for Category (category.contract, Category.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Category =

    /// The schema declared by category.contract (Category.v1).
    let rec schema : Schema<Category> =
        Schema.recordFor<Category, _> (fun name children ->
            { Name = name
              Children = children })
        |> Schema.field "name" _.Name (Schema.text |> Schema.constrainAll [ Constraint.minLength (1) ] |> Schema.describe "Stable display name.")
        |> Schema.field "children" _.Children (Schema.list (Schema.defer (fun () -> schema)) |> Schema.describe "Child categories use the same wire contract.")
        |> Schema.build
        |> Schema.describe "A recursive category tree used to prove self-references in generated schemas."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: Category) : Result<Category, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses raw boundary input through the schema.
    let parse (input: RawInput) : ParsedInput<Category, SchemaError> =
        Schema.parse schema input

    /// Typed field references for rules, redisplay, and UI binding.
    [<RequireQualifiedAccess>]
    module Fields =
        let name : FieldRef<Category, string> = { Name = "name"; Get = _.Name; Set = fun draft value -> { draft with Name = value } }
        let children : FieldRef<Category, Category list> = { Name = "children"; Get = _.Children; Set = fun draft value -> { draft with Children = value } }
