// <auto-generated>
//   Generated by axial schemagen from category.contract (Category.v1).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Axial.Tests.Generated

open Axial
open Axial.Validation
open Axial.Schema

/// A recursive category tree used to prove self-references in generated schemas.
type Category =
    {
        /// Stable display name.
        Name: string
        /// Child categories use the same wire contract.
        Children: Category list
    }

/// Schema and boundary functions for Category (category.contract, Category.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Category =

    open Axial.Schema.Syntax

    /// The schema declared by category.contract (Category.v1).
    let rec schema : Schema<Category> =
        SchemaCE.schema<Category> {
            SchemaCE.field "name" (fun (value: Category) -> value.Name) {
                withSchema (Schema.text |> Schema.describe "Stable display name.")
                constrain (minLength 1)
            }
            SchemaCE.field "children" (fun (value: Category) -> value.Children) {
                withSchema (Schema.listWith (Schema.defer (fun () -> schema)) |> Schema.describe "Child categories use the same wire contract.")
            }
            SchemaCE.construct (fun name children ->
                { Name = name
                  Children = children })
        }
        |> Schema.describe "A recursive category tree used to prove self-references in generated schemas."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: Category) : Result<Category, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<Category, Diagnostics<SchemaError>> =
        Schema.parse schema input
