// <auto-generated>
//   Generated by axial schemagen from category.contract (Category.v1).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Axial.Tests.Generated

open Axial.Validation
open Axial.Schema

/// A recursive category tree used to prove self-references in generated schemas.
type Category =
    {
        /// Stable display name.
        Name: string
        /// Child categories use the same wire contract.
        Children: Category list
    }

/// Schema and boundary functions for Category (category.contract, Category.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Category =

    /// The schema declared by category.contract (Category.v1).
    let rec schema : Schema<Category> =
        Schema.recordFor<Category, _> (fun name children ->
            { Name = name
              Children = children })
        |> Schema.fieldWith [ SchemaConstraint.minLength (1) ] "name" _.Name (Value.text |> Value.describe "Stable display name.")
        |> Schema.field "children" _.Children (Value.manyOf (Value.lazyOf (fun () -> schema)) |> Value.describe "Child categories use the same wire contract.")
        |> Schema.build
        |> Schema.describe "A recursive category tree used to prove self-references in generated schemas."

    /// Validates a draft built with an ordinary record literal, promoting it to a trusted model.
    let validate (draft: Category) : Result<Model<Category>, Diagnostics<SchemaError>> =
        Model.validate schema draft

    /// Parses raw boundary input through the schema.
    let parse (input: RawInput) : ParsedInput<Category, SchemaError> =
        Model.parse schema input

    /// Typed field references for rules, redisplay, and UI binding.
    [<RequireQualifiedAccess>]
    module Fields =
        let name : FieldRef<Category, string> = { Name = "name"; Get = _.Name }
        let children : FieldRef<Category, Category list> = { Name = "children"; Get = _.Children }
