// <auto-generated>
//   Generated by axial schemagen from geo.contract (Geo.v1).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Axial.Tests.Generated

open Axial
open Axial.Validation
open Axial.Schema

/// A geographic coordinate.
type Geo =
    {
        Lat: decimal
        Lon: decimal
    }

/// Schema and boundary functions for Geo (geo.contract, Geo.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Geo =

    open Axial.Schema.Syntax

    /// The schema declared by geo.contract (Geo.v1).
    let schema : Schema<Geo> =
        Schema.define<Geo>
        |> field "lat" _.Lat
        |> constrain (atLeast (-90m))
        |> constrain (atMost 90m)
        |> field "lon" _.Lon
        |> constrain (atLeast (-180m))
        |> constrain (atMost 180m)
        |> construct (fun lat lon ->
            { Lat = lat
              Lon = lon })
        |> Schema.describe "A geographic coordinate."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: Geo) : Result<Geo, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<Geo, Diagnostics<SchemaError>> =
        Schema.parse schema input
