// <auto-generated>
//   Generated by axial schemagen from geo.contract (Geo.v1).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Axial.Tests.Generated

open Axial.Validation
open Axial.Schema

/// A geographic coordinate.
type Geo =
    {
        Lat: decimal
        Lon: decimal
    }

/// Schema and boundary functions for Geo (geo.contract, Geo.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Geo =

    /// The schema declared by geo.contract (Geo.v1).
    let schema : Schema<Geo> =
        Schema.recordFor<Geo, _> (fun lat lon ->
            { Lat = lat
              Lon = lon })
        |> Schema.fieldWith [ SchemaConstraint.atLeast (-90m); SchemaConstraint.atMost (90m) ] "lat" _.Lat Value.decimal
        |> Schema.fieldWith [ SchemaConstraint.atLeast (-180m); SchemaConstraint.atMost (180m) ] "lon" _.Lon Value.decimal
        |> Schema.build
        |> Schema.describe "A geographic coordinate."

    /// Validates a draft built with an ordinary record literal, promoting it to a trusted model.
    let validate (draft: Geo) : Result<Model<Geo>, Diagnostics<SchemaError>> =
        Model.validate schema draft

    /// Parses raw boundary input through the schema.
    let parse (input: RawInput) : ParsedInput<Geo, SchemaError> =
        Model.parse schema input

    /// Typed field references for rules, redisplay, and UI binding.
    [<RequireQualifiedAccess>]
    module Fields =
        let lat : FieldRef<Geo, decimal> = { Name = "lat"; Get = _.Lat; Set = fun draft value -> { draft with Lat = value } }
        let lon : FieldRef<Geo, decimal> = { Name = "lon"; Get = _.Lon; Set = fun draft value -> { draft with Lon = value } }
