// <auto-generated>
//   Generated by axial schemagen from payment.contract (Card.v1, Invoice.v1, Payment.v1).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Axial.Tests.Generated

open Axial
open Axial.Validation
open Axial.Schema

/// A card payment source.
type Card =
    {
        Number: string
    }

/// Schema and boundary functions for Card (payment.contract, Card.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Card =

    open Axial.Schema.Syntax

    /// The schema declared by payment.contract (Card.v1).
    let schema : Schema<Card> =
        SchemaCE.schema<Card> {
            SchemaCE.field "number" (fun (value: Card) -> value.Number) {
                constrain (minLength 12)
                constrain (maxLength 19)
            }
            SchemaCE.construct (fun number ->
                { Number = number })
        }
        |> Schema.describe "A card payment source."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: Card) : Result<Card, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<Card, Diagnostics<SchemaError>> =
        Schema.parse schema input

/// An invoice payment source.
type Invoice =
    {
        Reference: string
    }

/// Schema and boundary functions for Invoice (payment.contract, Invoice.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Invoice =

    open Axial.Schema.Syntax

    /// The schema declared by payment.contract (Invoice.v1).
    let schema : Schema<Invoice> =
        SchemaCE.schema<Invoice> {
            SchemaCE.field "reference" (fun (value: Invoice) -> value.Reference) {
                constrain (minLength 1)
            }
            SchemaCE.construct (fun reference ->
                { Reference = reference })
        }
        |> Schema.describe "An invoice payment source."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: Invoice) : Result<Invoice, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<Invoice, Diagnostics<SchemaError>> =
        Schema.parse schema input

/// The "source" cases of Payment (payment.contract, Payment.v1).
[<RequireQualifiedAccess>]
type PaymentSource =
    | Card of Card
    | Invoice of Invoice

/// A payment method choice.
type Payment =
    {
        Source: PaymentSource
    }

/// Schema and boundary functions for Payment (payment.contract, Payment.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Payment =

    open Axial.Schema.Syntax

    let private sourceCases =
        [ UnionCase.create "card" PaymentSource.Card (function PaymentSource.Card payload -> Some payload | _ -> None) Card.schema
          UnionCase.create "invoice" PaymentSource.Invoice (function PaymentSource.Invoice payload -> Some payload | _ -> None) Invoice.schema ]

    /// The schema declared by payment.contract (Payment.v1).
    let schema : Schema<Payment> =
        SchemaCE.schema<Payment> {
            SchemaCE.field "source" (fun (value: Payment) -> value.Source) {
                withSchema (Schema.inlineUnion "kind" sourceCases)
            }
            SchemaCE.construct (fun source ->
                { Source = source })
        }
        |> Schema.describe "A payment method choice."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: Payment) : Result<Payment, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<Payment, Diagnostics<SchemaError>> =
        Schema.parse schema input
