// <auto-generated>
//   Generated by axial schemagen from payment.contract (Card.v1, Invoice.v1, Payment.v1).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Axial.Tests.Generated

open Axial.Validation
open Axial.Schema

/// A card payment source.
type Card =
    {
        Number: string
    }

/// Schema and boundary functions for Card (payment.contract, Card.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Card =

    /// The schema declared by payment.contract (Card.v1).
    let schema : Schema<Card> =
        Schema.recordFor<Card, _> (fun number ->
            { Number = number })
        |> Schema.fieldWith [ SchemaConstraint.minLength (12); SchemaConstraint.maxLength (19) ] "number" _.Number Value.text
        |> Schema.build
        |> Schema.describe "A card payment source."

    /// Validates a draft built with an ordinary record literal, promoting it to a trusted model.
    let validate (draft: Card) : Result<Model<Card>, Diagnostics<SchemaError>> =
        Model.validate schema draft

    /// Parses raw boundary input through the schema.
    let parse (input: RawInput) : ParsedInput<Card, SchemaError> =
        Model.parse schema input

    /// Typed field references for rules, redisplay, and UI binding.
    [<RequireQualifiedAccess>]
    module Fields =
        let number : FieldRef<Card, string> = { Name = "number"; Get = _.Number }

/// An invoice payment source.
type Invoice =
    {
        Reference: string
    }

/// Schema and boundary functions for Invoice (payment.contract, Invoice.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Invoice =

    /// The schema declared by payment.contract (Invoice.v1).
    let schema : Schema<Invoice> =
        Schema.recordFor<Invoice, _> (fun reference ->
            { Reference = reference })
        |> Schema.fieldWith [ SchemaConstraint.minLength (1) ] "reference" _.Reference Value.text
        |> Schema.build
        |> Schema.describe "An invoice payment source."

    /// Validates a draft built with an ordinary record literal, promoting it to a trusted model.
    let validate (draft: Invoice) : Result<Model<Invoice>, Diagnostics<SchemaError>> =
        Model.validate schema draft

    /// Parses raw boundary input through the schema.
    let parse (input: RawInput) : ParsedInput<Invoice, SchemaError> =
        Model.parse schema input

    /// Typed field references for rules, redisplay, and UI binding.
    [<RequireQualifiedAccess>]
    module Fields =
        let reference : FieldRef<Invoice, string> = { Name = "reference"; Get = _.Reference }

/// The "source" cases of Payment (payment.contract, Payment.v1).
[<RequireQualifiedAccess>]
type PaymentSource =
    | Card of Card
    | Invoice of Invoice

/// A payment method choice.
type Payment =
    {
        Source: PaymentSource
    }

/// Schema and boundary functions for Payment (payment.contract, Payment.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Payment =

    let private sourceCases =
        [ UnionCase.create "card" PaymentSource.Card (function PaymentSource.Card payload -> Some payload | _ -> None) (Value.nested Card.schema)
          UnionCase.create "invoice" PaymentSource.Invoice (function PaymentSource.Invoice payload -> Some payload | _ -> None) (Value.nested Invoice.schema) ]

    /// The schema declared by payment.contract (Payment.v1).
    let schema : Schema<Payment> =
        Schema.recordFor<Payment, _> (fun source ->
            { Source = source })
        |> Schema.field "source" _.Source (Value.unionInline "kind" sourceCases)
        |> Schema.build
        |> Schema.describe "A payment method choice."

    /// Validates a draft built with an ordinary record literal, promoting it to a trusted model.
    let validate (draft: Payment) : Result<Model<Payment>, Diagnostics<SchemaError>> =
        Model.validate schema draft

    /// Parses raw boundary input through the schema.
    let parse (input: RawInput) : ParsedInput<Payment, SchemaError> =
        Model.parse schema input

    /// Typed field references for rules, redisplay, and UI binding.
    [<RequireQualifiedAccess>]
    module Fields =
        let source : FieldRef<Payment, PaymentSource> = { Name = "source"; Get = _.Source }
