// <auto-generated>
//   Generated by axial schemagen from profile.contract (Profile.v1, Profile.v2).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Axial.Tests.Generated

open Axial
open Axial.Validation
open Axial.Schema

/// A user profile as first stored.
type ProfileV1 =
    {
        Name: string
        Email: string
    }

/// Schema and boundary functions for ProfileV1 (profile.contract, Profile.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module ProfileV1 =

    open Axial.Schema.Syntax

    /// The schema declared by profile.contract (Profile.v1).
    let schema : Schema<ProfileV1> =
        Schema.define<ProfileV1>
        |> field "name" _.Name
        |> constrain (minLength 1)
        |> constrain (maxLength 100)
        |> field "email" _.Email
        |> constrain emailFormat
        |> construct (fun name email ->
            { Name = name
              Email = email })
        |> Schema.describe "A user profile as first stored."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: ProfileV1) : Result<ProfileV1, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<ProfileV1, Diagnostics<SchemaError>> =
        Schema.parse schema input

/// A user profile with an explicit marketing consent decision.
type Profile =
    {
        Name: string
        Email: string
        MarketingOptIn: bool
    }

/// Schema and boundary functions for Profile (profile.contract, Profile.v2).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Profile =

    open Axial.Schema.Syntax

    /// The schema declared by profile.contract (Profile.v2).
    let schema : Schema<Profile> =
        Schema.define<Profile>
        |> field "name" _.Name
        |> constrain (minLength 1)
        |> constrain (maxLength 100)
        |> field "email" _.Email
        |> constrain emailFormat
        |> fieldWith (Schema.bool |> Schema.withDefault false) "marketing_opt_in" _.MarketingOptIn
        |> construct (fun name email marketingOptIn ->
            { Name = name
              Email = email
              MarketingOptIn = marketingOptIn })
        |> Schema.describe "A user profile with an explicit marketing consent decision."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: Profile) : Result<Profile, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<Profile, Diagnostics<SchemaError>> =
        Schema.parse schema input

    /// Builds the versioned wire contract; supply each n-1 -> n migration and the version-detection source.
    let contract
        (migrateV1ToV2: ProfileV1 -> Result<Profile, MigrationError>)
        (source: VersionSource)
        : Contract<Profile> =
        Contract.create "Profile" 2 schema
        |> Contract.supersedes 1 ProfileV1.schema migrateV1ToV2
        |> Contract.build source
