// <auto-generated>
//   Generated by axial schemagen from shipment.fs (PickupPoint.v1, CourierDelivery.v1, Shipment.v1, Shipment.v2).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Axial.Tests.Generated

open Axial
open Axial.Validation
open Axial.Schema

/// Schema and boundary functions for PickupPoint (shipment.fs, PickupPoint.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module PickupPoint =

    open Axial.Schema.Syntax

    /// The schema declared by shipment.fs (PickupPoint.v1).
    let schema : Schema<PickupPoint> =
        Schema.define<PickupPoint>
        |> field "code" _.Code
        |> construct (fun code ->
            { Code = code })
        |> Schema.describe "A named pickup location."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: PickupPoint) : Result<PickupPoint, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<PickupPoint, Diagnostics<SchemaError>> =
        Schema.parse schema input

/// Schema and boundary functions for CourierDelivery (shipment.fs, CourierDelivery.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module CourierDelivery =

    open Axial.Schema.Syntax

    /// The schema declared by shipment.fs (CourierDelivery.v1).
    let schema : Schema<CourierDelivery> =
        Schema.define<CourierDelivery>
        |> field "trackingUrl" _.TrackingUrl
        |> construct (fun trackingUrl ->
            { TrackingUrl = trackingUrl })
        |> Schema.describe "A courier delivery with tracking."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: CourierDelivery) : Result<CourierDelivery, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<CourierDelivery, Diagnostics<SchemaError>> =
        Schema.parse schema input

/// Schema and boundary functions for ShipmentV1 (shipment.fs, Shipment.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module ShipmentV1 =

    open Axial.Schema.Syntax

    /// The schema declared by shipment.fs (Shipment.v1).
    let schema : Schema<ShipmentV1> =
        Schema.define<ShipmentV1>
        |> fieldWith (Schema.text |> Schema.describe "Public shipment reference.") "reference" _.Reference
        |> constrain (pattern "^SH-[0-9]+$")
        |> field "notifyEmail" _.NotifyEmail
        |> constrain emailFormat
        |> field "items" _.Items
        |> construct (fun reference notifyEmail items ->
            { Reference = reference
              NotifyEmail = notifyEmail
              Items = items })
        |> Schema.describe "A shipment as first stored."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: ShipmentV1) : Result<ShipmentV1, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<ShipmentV1, Diagnostics<SchemaError>> =
        Schema.parse schema input

/// Schema and boundary functions for Shipment (shipment.fs, Shipment.v2).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Shipment =

    open Axial.Schema.Syntax

    let private priorityCases =
        [ EnumCase.create "standard" ShipmentPriority.Standard
          EnumCase.create "express" ShipmentPriority.Express
          EnumCase.create "same-day" ShipmentPriority.SameDay ]

    let private deliveryCases =
        [ UnionCase.create "pickup" DeliveryMethod.Pickup (function DeliveryMethod.Pickup payload -> Some payload | _ -> None) PickupPoint.schema
          UnionCase.create "courier" DeliveryMethod.Courier (function DeliveryMethod.Courier payload -> Some payload | _ -> None) CourierDelivery.schema ]

    /// The schema declared by shipment.fs (Shipment.v2).
    let schema : Schema<Shipment> =
        Schema.define<Shipment>
        |> fieldWith (Schema.text |> Schema.describe "Public shipment reference.") "reference" _.Reference
        |> constrain (pattern "^SH-[0-9]+$")
        |> field "notify_email" _.NotifyEmail
        |> constrain emailFormat
        |> field "items" _.Items
        |> field "tags" _.Tags
        |> constrain (minCount 1)
        |> constrain distinct
        |> field "weightKg" _.WeightKg
        |> constrain (atLeast 0.5m)
        |> fieldWith (Schema.enum priorityCases |> Schema.withDefault ShipmentPriority.Express) "priority" _.Priority
        |> fieldWith (Schema.inlineUnion "kind" deliveryCases) "delivery" _.Delivery
        |> fieldWith (Schema.option PickupPoint.schema) "origin" _.Origin
        |> fieldWith (Schema.int |> Schema.withDefault 1) "boxes" _.Boxes
        |> constrain (atLeast 1)
        |> construct (fun reference notifyEmail items tags weightKg priority delivery origin boxes ->
            { Reference = reference
              NotifyEmail = notifyEmail
              Items = items
              Tags = tags
              WeightKg = weightKg
              Priority = priority
              Delivery = delivery
              Origin = origin
              Boxes = boxes })
        |> Schema.describe "A shipment with delivery method, priority, and weight."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: Shipment) : Result<Shipment, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<Shipment, Diagnostics<SchemaError>> =
        Schema.parse schema input

    /// Builds the versioned wire contract; supply each n-1 -> n migration and the version-detection source.
    let contract
        (migrateV1ToV2: ShipmentV1 -> Result<Shipment, MigrationError>)
        (source: VersionSource)
        : Contract<Shipment> =
        Contract.create "Shipment" 2 schema
        |> Contract.supersedes 1 ShipmentV1.schema migrateV1ToV2
        |> Contract.build source
