// <auto-generated>
//   Generated by axial schemagen from shipment.fs (PickupPoint.v1, CourierDelivery.v1, Shipment.v1, Shipment.v2).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Axial.Tests.Generated

open Axial.Validation
open Axial.Schema

/// Schema and boundary functions for PickupPoint (shipment.fs, PickupPoint.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module PickupPoint =

    /// The schema declared by shipment.fs (PickupPoint.v1).
    let schema : Schema<PickupPoint> =
        Schema.recordFor<PickupPoint, _> (fun code ->
            { Code = code })
        |> Schema.field "code" _.Code Schema.text
        |> Schema.build
        |> Schema.describe "A named pickup location."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: PickupPoint) : Result<PickupPoint, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses raw boundary input through the schema.
    let parse (input: RawInput) : ParsedInput<PickupPoint, SchemaError> =
        Schema.parse schema input

    /// Typed field references for rules, redisplay, and UI binding.
    [<RequireQualifiedAccess>]
    module Fields =
        let code : FieldRef<PickupPoint, string> = { Name = "code"; Get = _.Code; Set = fun draft value -> { draft with Code = value } }

/// Schema and boundary functions for CourierDelivery (shipment.fs, CourierDelivery.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module CourierDelivery =

    /// The schema declared by shipment.fs (CourierDelivery.v1).
    let schema : Schema<CourierDelivery> =
        Schema.recordFor<CourierDelivery, _> (fun trackingUrl ->
            { TrackingUrl = trackingUrl })
        |> Schema.field "trackingUrl" _.TrackingUrl Schema.text
        |> Schema.build
        |> Schema.describe "A courier delivery with tracking."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: CourierDelivery) : Result<CourierDelivery, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses raw boundary input through the schema.
    let parse (input: RawInput) : ParsedInput<CourierDelivery, SchemaError> =
        Schema.parse schema input

    /// Typed field references for rules, redisplay, and UI binding.
    [<RequireQualifiedAccess>]
    module Fields =
        let trackingUrl : FieldRef<CourierDelivery, string> = { Name = "trackingUrl"; Get = _.TrackingUrl; Set = fun draft value -> { draft with TrackingUrl = value } }

/// Schema and boundary functions for ShipmentV1 (shipment.fs, Shipment.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module ShipmentV1 =

    /// The schema declared by shipment.fs (Shipment.v1).
    let schema : Schema<ShipmentV1> =
        Schema.recordFor<ShipmentV1, _> (fun reference notifyEmail items ->
            { Reference = reference
              NotifyEmail = notifyEmail
              Items = items })
        |> Schema.field "reference" _.Reference (Schema.text |> Schema.constrainAll [ Constraint.pattern ("^SH-[0-9]+$") ] |> Schema.describe "Public shipment reference.")
        |> Schema.field "notifyEmail" _.NotifyEmail (Schema.text |> Schema.constrainAll [ Constraint.email ])
        |> Schema.field "items" _.Items (Schema.map Schema.int)
        |> Schema.build
        |> Schema.describe "A shipment as first stored."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: ShipmentV1) : Result<ShipmentV1, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses raw boundary input through the schema.
    let parse (input: RawInput) : ParsedInput<ShipmentV1, SchemaError> =
        Schema.parse schema input

    /// Typed field references for rules, redisplay, and UI binding.
    [<RequireQualifiedAccess>]
    module Fields =
        let reference : FieldRef<ShipmentV1, string> = { Name = "reference"; Get = _.Reference; Set = fun draft value -> { draft with Reference = value } }
        let notifyEmail : FieldRef<ShipmentV1, string> = { Name = "notifyEmail"; Get = _.NotifyEmail; Set = fun draft value -> { draft with NotifyEmail = value } }
        let items : FieldRef<ShipmentV1, Map<string, int>> = { Name = "items"; Get = _.Items; Set = fun draft value -> { draft with Items = value } }

/// Schema and boundary functions for Shipment (shipment.fs, Shipment.v2).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Shipment =

    let private priorityCases =
        [ EnumCase.create "standard" ShipmentPriority.Standard
          EnumCase.create "express" ShipmentPriority.Express
          EnumCase.create "same-day" ShipmentPriority.SameDay ]

    let private deliveryCases =
        [ UnionCase.create "pickup" DeliveryMethod.Pickup (function DeliveryMethod.Pickup payload -> Some payload | _ -> None) PickupPoint.schema
          UnionCase.create "courier" DeliveryMethod.Courier (function DeliveryMethod.Courier payload -> Some payload | _ -> None) CourierDelivery.schema ]

    /// The schema declared by shipment.fs (Shipment.v2).
    let schema : Schema<Shipment> =
        Schema.recordFor<Shipment, _> (fun reference notifyEmail items tags weightKg priority delivery origin boxes ->
            { Reference = reference
              NotifyEmail = notifyEmail
              Items = items
              Tags = tags
              WeightKg = weightKg
              Priority = priority
              Delivery = delivery
              Origin = origin
              Boxes = boxes })
        |> Schema.field "reference" _.Reference (Schema.text |> Schema.constrainAll [ Constraint.pattern ("^SH-[0-9]+$") ] |> Schema.describe "Public shipment reference.")
        |> Schema.field "notify_email" _.NotifyEmail (Schema.text |> Schema.constrainAll [ Constraint.email ])
        |> Schema.field "items" _.Items (Schema.map Schema.int)
        |> Schema.field "tags" _.Tags (Schema.list Schema.text |> Schema.constrainAll [ Constraint.minCount (1); Constraint.distinct ])
        |> Schema.field "weightKg" _.WeightKg (Schema.decimal |> Schema.constrainAll [ Constraint.atLeast (0.5m) ])
        |> Schema.field "priority" _.Priority (Schema.enum priorityCases |> Schema.withDefault ShipmentPriority.Express)
        |> Schema.field "delivery" _.Delivery (Schema.inlineUnion "kind" deliveryCases)
        |> Schema.field "origin" _.Origin (Schema.option PickupPoint.schema)
        |> Schema.field "boxes" _.Boxes (Schema.int |> Schema.constrainAll [ Constraint.atLeast (1) ] |> Schema.withDefault 1)
        |> Schema.build
        |> Schema.describe "A shipment with delivery method, priority, and weight."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: Shipment) : Result<Shipment, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses raw boundary input through the schema.
    let parse (input: RawInput) : ParsedInput<Shipment, SchemaError> =
        Schema.parse schema input

    /// Builds the versioned wire contract; supply each n-1 -> n migration and the version-detection source.
    let contract
        (migrateV1ToV2: ShipmentV1 -> Result<Shipment, MigrationError>)
        (source: VersionSource)
        : Contract<Shipment> =
        Contract.create "Shipment" 2 schema
        |> Contract.supersedes 1 ShipmentV1.schema migrateV1ToV2
        |> Contract.build source

    /// Typed field references for rules, redisplay, and UI binding.
    [<RequireQualifiedAccess>]
    module Fields =
        let reference : FieldRef<Shipment, string> = { Name = "reference"; Get = _.Reference; Set = fun draft value -> { draft with Reference = value } }
        let notifyEmail : FieldRef<Shipment, string> = { Name = "notify_email"; Get = _.NotifyEmail; Set = fun draft value -> { draft with NotifyEmail = value } }
        let items : FieldRef<Shipment, Map<string, int>> = { Name = "items"; Get = _.Items; Set = fun draft value -> { draft with Items = value } }
        let tags : FieldRef<Shipment, string list> = { Name = "tags"; Get = _.Tags; Set = fun draft value -> { draft with Tags = value } }
        let weightKg : FieldRef<Shipment, decimal> = { Name = "weightKg"; Get = _.WeightKg; Set = fun draft value -> { draft with WeightKg = value } }
        let priority : FieldRef<Shipment, ShipmentPriority> = { Name = "priority"; Get = _.Priority; Set = fun draft value -> { draft with Priority = value } }
        let delivery : FieldRef<Shipment, DeliveryMethod> = { Name = "delivery"; Get = _.Delivery; Set = fun draft value -> { draft with Delivery = value } }
        let origin : FieldRef<Shipment, PickupPoint option> = { Name = "origin"; Get = _.Origin; Set = fun draft value -> { draft with Origin = value } }
        let boxes : FieldRef<Shipment, int> = { Name = "boxes"; Get = _.Boxes; Set = fun draft value -> { draft with Boxes = value } }
