// <auto-generated>
//   Generated by axial schemagen from signup.contract (Signup.v1).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Axial.Tests.Generated

open Axial.Validation
open Axial.Schema

/// The "plan" cases of Signup (signup.contract, Signup.v1).
[<RequireQualifiedAccess>]
type SignupPlan =
    | Free
    | Pro

/// A new account request.
type Signup =
    {
        /// Primary contact address.
        Email: string
        DisplayName: string option
        Age: int
        Plan: SignupPlan
        Tags: string list
        Limits: Map<string, int>
        Location: Geo option
    }

/// Schema and boundary functions for Signup (signup.contract, Signup.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Signup =

    open Axial.Schema.Syntax

    let private planCases =
        [ EnumCase.create "free" SignupPlan.Free
          EnumCase.create "pro" SignupPlan.Pro ]

    /// The schema declared by signup.contract (Signup.v1).
    let schema : Schema<Signup> =
        Schema.define<Signup>
        |> fieldWith (Schema.text |> Schema.constrainAll [ Constraint.email; Constraint.maxLength (254) ] |> Schema.describe "Primary contact address.") "email" _.Email
        |> fieldWith (Schema.option (Schema.text |> Schema.constrainAll [ Constraint.minLength (1); Constraint.maxLength (64) ])) "display_name" _.DisplayName
        |> fieldWith (Schema.int |> Schema.constrainAll [ Constraint.atLeast (13) ]) "age" _.Age
        |> fieldWith (Schema.enum planCases |> Schema.withDefault SignupPlan.Free) "plan" _.Plan
        |> fieldWith (Schema.listWith Schema.text |> Schema.constrainAll [ Constraint.maxCount (8); Constraint.distinct ]) "tags" _.Tags
        |> fieldWith (Schema.mapWith Schema.int) "limits" _.Limits
        |> fieldWith (Schema.option Geo.schema) "location" _.Location
        |> construct (fun email displayName age plan tags limits location ->
            { Email = email
              DisplayName = displayName
              Age = age
              Plan = plan
              Tags = tags
              Limits = limits
              Location = location })
        |> Schema.describe "A new account request."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: Signup) : Result<Signup, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses raw boundary input through the schema.
    let parse (input: RawInput) : ParsedInput<Signup, SchemaError> =
        Schema.parse schema input

    /// Typed field references for rules, redisplay, and UI binding.
    [<RequireQualifiedAccess>]
    module Fields =
        let email : FieldRef<Signup, string> = { Name = "email"; Get = _.Email; Set = fun draft value -> { draft with Email = value } }
        let displayName : FieldRef<Signup, string option> = { Name = "display_name"; Get = _.DisplayName; Set = fun draft value -> { draft with DisplayName = value } }
        let age : FieldRef<Signup, int> = { Name = "age"; Get = _.Age; Set = fun draft value -> { draft with Age = value } }
        let plan : FieldRef<Signup, SignupPlan> = { Name = "plan"; Get = _.Plan; Set = fun draft value -> { draft with Plan = value } }
        let tags : FieldRef<Signup, string list> = { Name = "tags"; Get = _.Tags; Set = fun draft value -> { draft with Tags = value } }
        let limits : FieldRef<Signup, Map<string, int>> = { Name = "limits"; Get = _.Limits; Set = fun draft value -> { draft with Limits = value } }
        let location : FieldRef<Signup, Geo option> = { Name = "location"; Get = _.Location; Set = fun draft value -> { draft with Location = value } }
