// <auto-generated>
//   Generated by axial schemagen from signup.contract (Signup.v1).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Axial.Tests.Generated

open Axial.Validation
open Axial.Schema

/// The "plan" cases of Signup (signup.contract, Signup.v1).
[<RequireQualifiedAccess>]
type SignupPlan =
    | Free
    | Pro

/// A new account request.
type Signup =
    {
        /// Primary contact address.
        Email: string
        DisplayName: string option
        Age: int
        Plan: SignupPlan
        Tags: string list
        Limits: Map<string, int>
        Location: Geo option
    }

/// Schema and boundary functions for Signup (signup.contract, Signup.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Signup =

    let private planCases =
        [ EnumCase.create "free" SignupPlan.Free
          EnumCase.create "pro" SignupPlan.Pro ]

    /// The schema declared by signup.contract (Signup.v1).
    let schema : Schema<Signup> =
        Schema.recordFor<Signup, _> (fun email displayName age plan tags limits location ->
            { Email = email
              DisplayName = displayName
              Age = age
              Plan = plan
              Tags = tags
              Limits = limits
              Location = location })
        |> Schema.fieldWith [ SchemaConstraint.email; SchemaConstraint.maxLength (254) ] "email" _.Email (Value.text |> Value.describe "Primary contact address.")
        |> Schema.field "display_name" _.DisplayName (Value.optionOf (Value.text |> Value.withConstraints [ SchemaConstraint.minLength (1); SchemaConstraint.maxLength (64) ]))
        |> Schema.fieldWith [ SchemaConstraint.atLeast (13) ] "age" _.Age Value.int
        |> Schema.field "plan" _.Plan (Value.enumOf planCases |> Value.withDefault SignupPlan.Free)
        |> Schema.fieldWith [ SchemaConstraint.maxCount (8); SchemaConstraint.distinct ] "tags" _.Tags (Value.manyOf Value.text)
        |> Schema.field "limits" _.Limits (Value.map Value.int)
        |> Schema.field "location" _.Location (Value.optionOf (Value.nested Geo.schema))
        |> Schema.build
        |> Schema.describe "A new account request."

    /// Validates a draft built with an ordinary record literal, promoting it to a trusted model.
    let validate (draft: Signup) : Result<Model<Signup>, Diagnostics<SchemaError>> =
        Model.validate schema draft

    /// Parses raw boundary input through the schema.
    let parse (input: RawInput) : ParsedInput<Signup, SchemaError> =
        Model.parse schema input

    /// Typed field references for rules, redisplay, and UI binding.
    [<RequireQualifiedAccess>]
    module Fields =
        let email : FieldRef<Signup, string> = { Name = "email"; Get = _.Email }
        let displayName : FieldRef<Signup, string option> = { Name = "display_name"; Get = _.DisplayName }
        let age : FieldRef<Signup, int> = { Name = "age"; Get = _.Age }
        let plan : FieldRef<Signup, SignupPlan> = { Name = "plan"; Get = _.Plan }
        let tags : FieldRef<Signup, string list> = { Name = "tags"; Get = _.Tags }
        let limits : FieldRef<Signup, Map<string, int>> = { Name = "limits"; Get = _.Limits }
        let location : FieldRef<Signup, Geo option> = { Name = "location"; Get = _.Location }
