// <auto-generated>
//   Generated by axial schemagen from signup.contract (Signup.v1).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Axial.Tests.Generated

open Axial
open Axial.Validation
open Axial.Schema

/// The "plan" cases of Signup (signup.contract, Signup.v1).
[<RequireQualifiedAccess>]
type SignupPlan =
    | Free
    | Pro

/// A new account request.
type Signup =
    {
        /// Primary contact address.
        Email: string
        DisplayName: string option
        Age: int
        Plan: SignupPlan
        Tags: string list
        Limits: Map<string, int>
        Location: Geo option
    }

/// Schema and boundary functions for Signup (signup.contract, Signup.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Signup =

    open Axial.Schema.Syntax

    let private planCases =
        [ EnumCase.create "free" SignupPlan.Free
          EnumCase.create "pro" SignupPlan.Pro ]

    /// The schema declared by signup.contract (Signup.v1).
    let schema : Schema<Signup> =
        Schema.define<Signup>
        |> fieldWith (Schema.text |> Schema.describe "Primary contact address.") "email" _.Email
        |> constrain emailFormat
        |> constrain (maxLength 254)
        |> fieldWith (Schema.option (Schema.text |> Schema.constrainAll [ Constraint.minLength (1); Constraint.maxLength (64) ])) "display_name" _.DisplayName
        |> field "age" _.Age
        |> constrain (atLeast 13)
        |> fieldWith (Schema.enum planCases |> Schema.withDefault SignupPlan.Free) "plan" _.Plan
        |> field "tags" _.Tags
        |> constrain (maxCount 8)
        |> constrain distinct
        |> field "limits" _.Limits
        |> fieldWith (Schema.option Geo.schema) "location" _.Location
        |> construct (fun email displayName age plan tags limits location ->
            { Email = email
              DisplayName = displayName
              Age = age
              Plan = plan
              Tags = tags
              Limits = limits
              Location = location })
        |> Schema.describe "A new account request."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: Signup) : Result<Signup, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<Signup, Diagnostics<SchemaError>> =
        Schema.parse schema input
