// <auto-generated>
//   Generated by reified schemagen from workspace.fs (WorkspaceCard.v1, WorkspaceCard.v2).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Reified.ReferenceApp.Wire

open Reified
open Reified.SchemaDSL

[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Visibility =

    type private Model = Visibility
    let schema =
        Schema.enum [
            EnumCase.create "private" Model.Private
            EnumCase.create "team" Model.Team
            EnumCase.create "org-wide" Model.OrgWide
        ]

/// Schema for WorkspaceCardV1.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module WorkspaceCardV1 =

    open Reified.ConstraintDSL
    type private Model = WorkspaceCardV1
    open type Model

    let schema =
        schema<Model> {
            fieldAs "name" _.Name {
                describe "Display name of the workspace."
                constraints [
                    minLength 1
                    maxLength 60
                ]
            }
            fieldAs "owner" _.Owner
            construct (fun name owner ->
                { Name = name
                  Owner = owner })
        }
        |> Schema.describe "A workspace card as first exported: one owner string of the form \"Name <email>\"."

    let validate = Schema.check schema
    let parse = Schema.parse schema

/// Schema for WorkspaceCard.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module WorkspaceCard =

    open Reified.ConstraintDSL
    type private Model = WorkspaceCard
    open type Model

    let schema =
        schema<Model> {
            fieldAs "name" _.Name {
                describe "Display name of the workspace."
                constraints [
                    minLength 1
                    maxLength 60
                ]
            }
            fieldAs "owner_email" _.OwnerEmail {
                constrain email
            }
            fieldAs "visibility" _.Visibility {
                withSchema (Visibility.schema |> Schema.withDefault Visibility.Private)
            }
            fieldAs "members" _.Members {
                constrain Constraint.distinct
            }
            construct (fun name ownerEmail visibility members -> WorkspaceCard.create name ownerEmail visibility members)
        }
        |> Schema.describe "A workspace card with a dedicated owner email, visibility, and member emails."

    let validate = Schema.check schema
    let parse = Schema.parse schema

    /// Builds the versioned wire contract; supply each n-1 -> n migration and the version-detection source.
    let contract
        (migrateV1ToV2: WorkspaceCardV1 -> Result<WorkspaceCard, MigrationError>)
        (source: VersionSource)
        : Contract<WorkspaceCard> =
        Contract.create "WorkspaceCard" 2 schema
        |> Contract.supersedes 1 WorkspaceCardV1.schema migrateV1ToV2
        |> Contract.build source
