// <auto-generated>
//   Generated by reified schemagen from workspace.fs (WorkspaceCard.v1, WorkspaceCard.v2).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Reified.ReferenceApp.Wire

open Reified

/// Schema and boundary functions for WorkspaceCardV1 (workspace.fs, WorkspaceCard.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module WorkspaceCardV1 =

    open Reified.SchemaDSL
    open Reified.ConstraintDSL
    open type WorkspaceCardV1

    /// The schema declared by workspace.fs (WorkspaceCard.v1).
    let schema =
        schema<WorkspaceCardV1> {
            fieldAs "name" _.Name {
                withSchema (Schema.text |> Schema.describe "Display name of the workspace.")
                constraints [
                    minLength 1
                    maxLength 60
                ]
            }
            fieldAs "owner" _.Owner
            construct (fun name owner ->
                { Name = name
                  Owner = owner })
        }
        |> Schema.describe "A workspace card as first exported: one owner string of the form \"Name <email>\"."

    /// Validates an ordinary record-literal draft of WorkspaceCardV1.
    let validate (draft: WorkspaceCardV1) : Result<WorkspaceCardV1, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data into WorkspaceCardV1.
    let parse (input: Data) : Result<WorkspaceCardV1, SchemaErrors> =
        Schema.parse schema input

/// Schema and boundary functions for WorkspaceCard (workspace.fs, WorkspaceCard.v2).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module WorkspaceCard =

    open Reified.SchemaDSL
    open Reified.ConstraintDSL
    open type WorkspaceCard

    let private visibilityCases =
        [ EnumCase.create "private" Visibility.Private
          EnumCase.create "team" Visibility.Team
          EnumCase.create "org-wide" Visibility.OrgWide ]

    /// The schema declared by workspace.fs (WorkspaceCard.v2).
    let schema =
        schema<WorkspaceCard> {
            fieldAs "name" _.Name {
                withSchema (Schema.text |> Schema.describe "Display name of the workspace.")
                constraints [
                    minLength 1
                    maxLength 60
                ]
            }
            fieldAs "owner_email" _.OwnerEmail {
                constrain email
            }
            fieldAs "visibility" _.Visibility {
                withSchema (Schema.enum visibilityCases |> Schema.withDefault Visibility.Private)
            }
            fieldAs "members" _.Members {
                constrain Constraint.distinct
            }
            construct (fun name ownerEmail visibility members -> WorkspaceCard.create name ownerEmail visibility members)
        }
        |> Schema.describe "A workspace card with a dedicated owner email, visibility, and member emails."

    /// Validates an ordinary record-literal draft of WorkspaceCard.
    let validate (draft: WorkspaceCard) : Result<WorkspaceCard, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data into WorkspaceCard.
    let parse (input: Data) : Result<WorkspaceCard, SchemaErrors> =
        Schema.parse schema input

    /// Builds the versioned wire contract; supply each n-1 -> n migration and the version-detection source.
    let contract
        (migrateV1ToV2: WorkspaceCardV1 -> Result<WorkspaceCard, MigrationError>)
        (source: VersionSource)
        : Contract<WorkspaceCard> =
        Contract.create "WorkspaceCard" 2 schema
        |> Contract.supersedes 1 WorkspaceCardV1.schema migrateV1ToV2
        |> Contract.build source
