<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Axial.Refined" Version="$(AxialPackageVersion)" />
    <PackageReference Include="Axial.Schema" Version="$(AxialPackageVersion)" />
    <PackageReference Include="FsToolkit.ErrorHandling" Version="4.18.0" />
  </ItemGroup>

</Project>
