<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Reified.Refinements" Version="$(ReifiedPackageVersion)" />
    <PackageReference Include="Reified.Schema" Version="$(ReifiedPackageVersion)" />
    <PackageReference Include="FsToolkit.ErrorHandling" Version="4.18.0" />
  </ItemGroup>

</Project>
