// <auto-generated>
//   Generated by reified schemagen from category.contract (Category.v1).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
// Recursive schemas intentionally defer self-reference; suppress the recursive-value initialization warning.
#nowarn "40"
namespace Reified.Tests.Generated

open Reified
open Reified.SchemaDSL

/// A recursive category tree used to prove self-references in generated schemas.
type Category =
    {
        /// Stable display name.
        Name: string
        /// Child categories use the same wire contract.
        Children: Category list
    }

/// Schema for Category.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Category =

    open Reified.ConstraintDSL
    type private Model = Category
    open type Model

    let rec schema =
        SchemaDSL.schema<Model> {
            fieldAs "name" _.Name {
                describe "Stable display name."
                constrain (minLength 1)
            }
            fieldAs "children" _.Children {
                withSchema (Schema.listWith (Schema.defer (fun () -> schema)) |> Schema.describe "Child categories use the same wire contract.")
            }
            construct (fun name children ->
                { Name = name
                  Children = children })
        }
        |> Schema.describe "A recursive category tree used to prove self-references in generated schemas."

    let validate = Schema.check schema
    let parse = Schema.parse schema
