// <auto-generated>
//   Generated by reified schemagen from category.contract (Category.v1).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
// Recursive schemas intentionally defer self-reference; suppress the recursive-value initialization warning.
#nowarn "40"
namespace Reified.Tests.Generated

open Reified

/// A recursive category tree used to prove self-references in generated schemas.
type Category =
    {
        /// Stable display name.
        Name: string
        /// Child categories use the same wire contract.
        Children: Category list
    }

/// Schema and boundary functions for Category (category.contract, Category.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Category =

    open Reified.SchemaDSL
    open Reified.ConstraintDSL
    open type Category

    /// The schema declared by category.contract (Category.v1).
    let rec schema =
        SchemaDSL.schema<Category> {
            fieldAs "name" _.Name {
                withSchema (Schema.text |> Schema.describe "Stable display name.")
                constrain (minLength 1)
            }
            fieldAs "children" _.Children {
                withSchema (Schema.listWith (Schema.defer (fun () -> schema)) |> Schema.describe "Child categories use the same wire contract.")
            }
            construct (fun name children ->
                { Name = name
                  Children = children })
        }
        |> Schema.describe "A recursive category tree used to prove self-references in generated schemas."

    /// Validates an ordinary record-literal draft of Category.
    let validate (draft: Category) : Result<Category, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data into Category.
    let parse (input: Data) : Result<Category, SchemaErrors> =
        Schema.parse schema input
