// <auto-generated>
//   Generated by reified schemagen from geo.contract (Geo.v1).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Reified.Tests.Generated

open Reified
open Reified.Constraint
open Reified.Schema

/// A geographic coordinate.
type Geo =
    {
        Lat: decimal
        Lon: decimal
    }

/// Schema and boundary functions for Geo (geo.contract, Geo.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Geo =

    open Reified.Schema.Syntax
    open Reified.Constraint.Syntax

    /// The schema declared by geo.contract (Geo.v1).
    let schema : Schema<Geo> =
        schema<Geo> {
            fieldAs "lat" (fun (value: Geo) -> value.Lat) {
                constraints [
                    atLeast (-90m)
                    atMost 90m
                ]
            }
            fieldAs "lon" (fun (value: Geo) -> value.Lon) {
                constraints [
                    atLeast (-180m)
                    atMost 180m
                ]
            }
            construct (fun lat lon ->
                { Lat = lat
                  Lon = lon })
        }
        |> Schema.describe "A geographic coordinate."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: Geo) : Result<Geo, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<Geo, SchemaErrors> =
        Schema.parse schema input
