// <auto-generated>
//   Generated by reified schemagen from geo.contract (Geo.v1).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Reified.Tests.Generated

open Reified

/// A geographic coordinate.
type Geo =
    {
        Lat: decimal
        Lon: decimal
    }

/// Schema and boundary functions for Geo (geo.contract, Geo.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Geo =

    open Reified.SchemaDSL
    open Reified.ConstraintDSL
    open type Geo

    /// The schema declared by geo.contract (Geo.v1).
    let schema =
        schema<Geo> {
            fieldAs "lat" _.Lat {
                constraints [
                    atLeast (-90m)
                    atMost 90m
                ]
            }
            fieldAs "lon" _.Lon {
                constraints [
                    atLeast (-180m)
                    atMost 180m
                ]
            }
            construct (fun lat lon ->
                { Lat = lat
                  Lon = lon })
        }
        |> Schema.describe "A geographic coordinate."

    /// Validates an ordinary record-literal draft of Geo.
    let validate (draft: Geo) : Result<Geo, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data into Geo.
    let parse (input: Data) : Result<Geo, SchemaErrors> =
        Schema.parse schema input
