// <auto-generated>
//   Generated by reified schemagen from payment.contract (Card.v1, Invoice.v1, Payment.v1).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Reified.Tests.Generated

open Reified

/// A card payment source.
type Card =
    {
        Number: string
    }

/// Schema and boundary functions for Card (payment.contract, Card.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Card =

    open Reified.SchemaDSL
    open Reified.ConstraintDSL
    open type Card

    /// The schema declared by payment.contract (Card.v1).
    let schema =
        schema<Card> {
            fieldAs "number" _.Number {
                constraints [
                    minLength 12
                    maxLength 19
                ]
            }
            construct (fun number ->
                { Number = number })
        }
        |> Schema.describe "A card payment source."

    /// Validates an ordinary record-literal draft of Card.
    let validate (draft: Card) : Result<Card, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data into Card.
    let parse (input: Data) : Result<Card, SchemaErrors> =
        Schema.parse schema input

/// An invoice payment source.
type Invoice =
    {
        Reference: string
    }

/// Schema and boundary functions for Invoice (payment.contract, Invoice.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Invoice =

    open Reified.SchemaDSL
    open Reified.ConstraintDSL
    open type Invoice

    /// The schema declared by payment.contract (Invoice.v1).
    let schema =
        schema<Invoice> {
            fieldAs "reference" _.Reference {
                constrain (minLength 1)
            }
            construct (fun reference ->
                { Reference = reference })
        }
        |> Schema.describe "An invoice payment source."

    /// Validates an ordinary record-literal draft of Invoice.
    let validate (draft: Invoice) : Result<Invoice, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data into Invoice.
    let parse (input: Data) : Result<Invoice, SchemaErrors> =
        Schema.parse schema input

/// The "source" cases of Payment (payment.contract, Payment.v1).
[<RequireQualifiedAccess>]
type PaymentSource =
    | Card of Card
    | Invoice of Invoice

/// A payment method choice.
type Payment =
    {
        Source: PaymentSource
    }

/// Schema and boundary functions for Payment (payment.contract, Payment.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Payment =

    open Reified.SchemaDSL
    open Reified.ConstraintDSL
    open type Payment

    let private sourceCases =
        [ UnionCase.fields "card" PaymentSource.Card (function PaymentSource.Card payload -> Some payload | _ -> None) Card.schema
          UnionCase.fields "invoice" PaymentSource.Invoice (function PaymentSource.Invoice payload -> Some payload | _ -> None) Invoice.schema ]

    /// The schema declared by payment.contract (Payment.v1).
    let schema =
        schema<Payment> {
            fieldAs "source" _.Source {
                withSchema (Schema.unionWith (UnionRepresentation.Internal "kind") sourceCases)
            }
            construct (fun source ->
                { Source = source })
        }
        |> Schema.describe "A payment method choice."

    /// Validates an ordinary record-literal draft of Payment.
    let validate (draft: Payment) : Result<Payment, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data into Payment.
    let parse (input: Data) : Result<Payment, SchemaErrors> =
        Schema.parse schema input
