// <auto-generated>
//   Generated by reified schemagen from payment.contract (Card.v1, Invoice.v1, Payment.v1).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Reified.Tests.Generated

open Reified
open Reified.SchemaDSL

/// A card payment source.
type Card =
    {
        Number: string
    }

/// Schema for Card.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Card =

    open Reified.ConstraintDSL
    type private Model = Card
    open type Model

    let schema =
        schema<Model> {
            fieldAs "number" _.Number {
                constraints [
                    minLength 12
                    maxLength 19
                ]
            }
            construct (fun number ->
                { Number = number })
        }
        |> Schema.describe "A card payment source."

    let validate = Schema.check schema
    let parse = Schema.parse schema

/// An invoice payment source.
type Invoice =
    {
        Reference: string
    }

/// Schema for Invoice.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Invoice =

    open Reified.ConstraintDSL
    type private Model = Invoice
    open type Model

    let schema =
        schema<Model> {
            fieldAs "reference" _.Reference {
                constrain (minLength 1)
            }
            construct (fun reference ->
                { Reference = reference })
        }
        |> Schema.describe "An invoice payment source."

    let validate = Schema.check schema
    let parse = Schema.parse schema

/// The "source" cases of Payment (payment.contract, Payment.v1).
[<RequireQualifiedAccess>]
type PaymentSource =
    | Card of Card
    | Invoice of Invoice

/// A payment method choice.
type Payment =
    {
        Source: PaymentSource
    }

/// Schema for Payment.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Payment =

    type private Model = Payment
    open type Model

    let private sourceCases =
        [ UnionCase.fields "card" PaymentSource.Card (function PaymentSource.Card payload -> Some payload | _ -> None) Card.schema
          UnionCase.fields "invoice" PaymentSource.Invoice (function PaymentSource.Invoice payload -> Some payload | _ -> None) Invoice.schema ]

    let schema =
        schema<Model> {
            fieldAs "source" _.Source {
                withSchema (Schema.unionWith (UnionRepresentation.Internal "kind") sourceCases)
            }
            construct (fun source ->
                { Source = source })
        }
        |> Schema.describe "A payment method choice."

    let validate = Schema.check schema
    let parse = Schema.parse schema
