// <auto-generated>
//   Generated by reified schemagen from profile.contract (Profile.v1, Profile.v2).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Reified.Tests.Generated

open Reified

/// A user profile as first stored.
type ProfileV1 =
    {
        Name: string
        Email: string
    }

/// Schema and boundary functions for ProfileV1 (profile.contract, Profile.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module ProfileV1 =

    open Reified.SchemaDSL
    open Reified.ConstraintDSL
    open type ProfileV1

    /// The schema declared by profile.contract (Profile.v1).
    let schema =
        schema<ProfileV1> {
            fieldAs "name" _.Name {
                constraints [
                    minLength 1
                    maxLength 100
                ]
            }
            fieldAs "email" _.Email {
                constrain email
            }
            construct (fun name email ->
                { Name = name
                  Email = email })
        }
        |> Schema.describe "A user profile as first stored."

    /// Validates an ordinary record-literal draft of ProfileV1.
    let validate (draft: ProfileV1) : Result<ProfileV1, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data into ProfileV1.
    let parse (input: Data) : Result<ProfileV1, SchemaErrors> =
        Schema.parse schema input

/// A user profile with an explicit marketing consent decision.
type Profile =
    {
        Name: string
        Email: string
        MarketingOptIn: bool
    }

/// Schema and boundary functions for Profile (profile.contract, Profile.v2).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Profile =

    open Reified.SchemaDSL
    open Reified.ConstraintDSL
    open type Profile

    /// The schema declared by profile.contract (Profile.v2).
    let schema =
        schema<Profile> {
            fieldAs "name" _.Name {
                constraints [
                    minLength 1
                    maxLength 100
                ]
            }
            fieldAs "email" _.Email {
                constrain email
            }
            fieldAs "marketing_opt_in" _.MarketingOptIn {
                withSchema (Schema.bool |> Schema.withDefault false)
            }
            construct (fun name email marketingOptIn ->
                { Name = name
                  Email = email
                  MarketingOptIn = marketingOptIn })
        }
        |> Schema.describe "A user profile with an explicit marketing consent decision."

    /// Validates an ordinary record-literal draft of Profile.
    let validate (draft: Profile) : Result<Profile, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data into Profile.
    let parse (input: Data) : Result<Profile, SchemaErrors> =
        Schema.parse schema input

    /// Builds the versioned wire contract; supply each n-1 -> n migration and the version-detection source.
    let contract
        (migrateV1ToV2: ProfileV1 -> Result<Profile, MigrationError>)
        (source: VersionSource)
        : Contract<Profile> =
        Contract.create "Profile" 2 schema
        |> Contract.supersedes 1 ProfileV1.schema migrateV1ToV2
        |> Contract.build source
