// <auto-generated>
//   Generated by reified schemagen from profile.contract (Profile.v1, Profile.v2).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Reified.Tests.Generated

open Reified
open Reified.SchemaDSL

/// A user profile as first stored.
type ProfileV1 =
    {
        Name: string
        Email: string
    }

/// Schema for ProfileV1.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module ProfileV1 =

    open Reified.ConstraintDSL
    type private Model = ProfileV1
    open type Model

    let schema =
        schema<Model> {
            fieldAs "name" _.Name {
                constraints [
                    minLength 1
                    maxLength 100
                ]
            }
            fieldAs "email" _.Email {
                constrain email
            }
            construct (fun name email ->
                { Name = name
                  Email = email })
        }
        |> Schema.describe "A user profile as first stored."

    let validate = Schema.check schema
    let parse = Schema.parse schema

/// A user profile with an explicit marketing consent decision.
type Profile =
    {
        Name: string
        Email: string
        MarketingOptIn: bool
    }

/// Schema for Profile.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Profile =

    open Reified.ConstraintDSL
    type private Model = Profile
    open type Model

    let schema =
        schema<Model> {
            fieldAs "name" _.Name {
                constraints [
                    minLength 1
                    maxLength 100
                ]
            }
            fieldAs "email" _.Email {
                constrain email
            }
            fieldAs "marketing_opt_in" _.MarketingOptIn {
                defaultValue false
            }
            construct (fun name email marketingOptIn ->
                { Name = name
                  Email = email
                  MarketingOptIn = marketingOptIn })
        }
        |> Schema.describe "A user profile with an explicit marketing consent decision."

    let validate = Schema.check schema
    let parse = Schema.parse schema

    /// Builds the versioned wire contract; supply each n-1 -> n migration and the version-detection source.
    let contract
        (migrateV1ToV2: ProfileV1 -> Result<Profile, MigrationError>)
        (source: VersionSource)
        : Contract<Profile> =
        Contract.create "Profile" 2 schema
        |> Contract.supersedes 1 ProfileV1.schema migrateV1ToV2
        |> Contract.build source
