// <auto-generated>
//   Generated by reified schemagen from shipment.fs (PickupPoint.v1, CourierDelivery.v1, Shipment.v1, Shipment.v2).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Reified.Tests.Generated

open Reified
open Reified.SchemaDSL

[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module ShipmentPriority =

    type private Model = ShipmentPriority
    let schema =
        Schema.enum [
            EnumCase.create "standard" Model.Standard
            EnumCase.create "express" Model.Express
            EnumCase.create "same-day" Model.SameDay
        ]

/// Schema for PickupPoint.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module PickupPoint =

    type private Model = PickupPoint
    open type Model

    let schema =
        schema<Model> {
            fieldAs "code" _.Code
            construct (fun code ->
                { Code = code })
        }
        |> Schema.describe "A named pickup location."

    let validate = Schema.check schema
    let parse = Schema.parse schema

/// Schema for CourierDelivery.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module CourierDelivery =

    type private Model = CourierDelivery
    open type Model

    let schema =
        schema<Model> {
            fieldAs "trackingUrl" _.TrackingUrl
            construct (fun trackingUrl ->
                { TrackingUrl = trackingUrl })
        }
        |> Schema.describe "A courier delivery with tracking."

    let validate = Schema.check schema
    let parse = Schema.parse schema

/// Schema for ShipmentV1.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module ShipmentV1 =

    open Reified.ConstraintDSL
    type private Model = ShipmentV1
    open type Model

    let schema =
        schema<Model> {
            fieldAs "reference" _.Reference {
                describe "Public shipment reference."
                constrain (pattern "^SH-[0-9]+$")
            }
            fieldAs "notifyEmail" _.NotifyEmail {
                constrain email
            }
            fieldAs "items" _.Items
            construct (fun reference notifyEmail items ->
                { Reference = reference
                  NotifyEmail = notifyEmail
                  Items = items })
        }
        |> Schema.describe "A shipment as first stored."

    let validate = Schema.check schema
    let parse = Schema.parse schema

[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module DeliveryMethod =

    type private Model = DeliveryMethod
    open type Model

    let schema =
        Schema.unionWith (UnionRepresentation.Internal "kind") [
            UnionCase.fields "pickup" Pickup (function Pickup payload -> Some payload | _ -> None) PickupPoint.schema
            UnionCase.fields "courier" Courier (function Courier payload -> Some payload | _ -> None) CourierDelivery.schema
        ]

/// Schema for Shipment.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Shipment =

    open Reified.ConstraintDSL
    type private Model = Shipment
    open type Model

    let schema =
        schema<Model> {
            fieldAs "reference" _.Reference {
                describe "Public shipment reference."
                constrain (pattern "^SH-[0-9]+$")
            }
            fieldAs "notify_email" _.NotifyEmail {
                constrain email
            }
            fieldAs "items" _.Items
            fieldAs "tags" _.Tags {
                constraints [
                    minLength 1
                    Constraint.distinct
                ]
            }
            fieldAs "weightKg" _.WeightKg {
                constrain (atLeast 0.5m)
            }
            fieldAs "priority" _.Priority {
                withSchema (ShipmentPriority.schema |> Schema.withDefault ShipmentPriority.Express)
            }
            fieldAs "delivery" _.Delivery {
                withSchema DeliveryMethod.schema
            }
            fieldAs "origin" _.Origin {
                withSchema (Schema.option PickupPoint.schema)
            }
            fieldAs "boxes" _.Boxes {
                defaultValue 1
                constrain (atLeast 1)
            }
            construct (fun reference notifyEmail items tags weightKg priority delivery origin boxes ->
                { Reference = reference
                  NotifyEmail = notifyEmail
                  Items = items
                  Tags = tags
                  WeightKg = weightKg
                  Priority = priority
                  Delivery = delivery
                  Origin = origin
                  Boxes = boxes })
        }
        |> Schema.describe "A shipment with delivery method, priority, and weight."

    let validate = Schema.check schema
    let parse = Schema.parse schema

    /// Builds the versioned wire contract; supply each n-1 -> n migration and the version-detection source.
    let contract
        (migrateV1ToV2: ShipmentV1 -> Result<Shipment, MigrationError>)
        (source: VersionSource)
        : Contract<Shipment> =
        Contract.create "Shipment" 2 schema
        |> Contract.supersedes 1 ShipmentV1.schema migrateV1ToV2
        |> Contract.build source
