// <auto-generated>
//   Generated by reified schemagen from shipment.fs (PickupPoint.v1, CourierDelivery.v1, Shipment.v1, Shipment.v2).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Reified.Tests.Generated

open Reified

/// Schema and boundary functions for PickupPoint (shipment.fs, PickupPoint.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module PickupPoint =

    open Reified.SchemaDSL
    open Reified.ConstraintDSL

    /// The schema declared by shipment.fs (PickupPoint.v1).
    let schema : Schema<PickupPoint> =
        schema<PickupPoint> {
            fieldAs "code" (fun (value: PickupPoint) -> value.Code)
            construct (fun code ->
                { PickupPoint.Code = code })
        }
        |> Schema.describe "A named pickup location."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: PickupPoint) : Result<PickupPoint, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<PickupPoint, SchemaErrors> =
        Schema.parse schema input

/// Schema and boundary functions for CourierDelivery (shipment.fs, CourierDelivery.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module CourierDelivery =

    open Reified.SchemaDSL
    open Reified.ConstraintDSL

    /// The schema declared by shipment.fs (CourierDelivery.v1).
    let schema : Schema<CourierDelivery> =
        schema<CourierDelivery> {
            fieldAs "trackingUrl" (fun (value: CourierDelivery) -> value.TrackingUrl)
            construct (fun trackingUrl ->
                { CourierDelivery.TrackingUrl = trackingUrl })
        }
        |> Schema.describe "A courier delivery with tracking."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: CourierDelivery) : Result<CourierDelivery, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<CourierDelivery, SchemaErrors> =
        Schema.parse schema input

/// Schema and boundary functions for ShipmentV1 (shipment.fs, Shipment.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module ShipmentV1 =

    open Reified.SchemaDSL
    open Reified.ConstraintDSL

    /// The schema declared by shipment.fs (Shipment.v1).
    let schema : Schema<ShipmentV1> =
        schema<ShipmentV1> {
            fieldAs "reference" (fun (value: ShipmentV1) -> value.Reference) {
                withSchema (Schema.text |> Schema.describe "Public shipment reference.")
                constrain (pattern "^SH-[0-9]+$")
            }
            fieldAs "notifyEmail" (fun (value: ShipmentV1) -> value.NotifyEmail) {
                constrain email
            }
            fieldAs "items" (fun (value: ShipmentV1) -> value.Items) {
                withSchema (Schema.mapWith Schema.int)
            }
            construct (fun reference notifyEmail items ->
                { ShipmentV1.Reference = reference
                  ShipmentV1.NotifyEmail = notifyEmail
                  ShipmentV1.Items = items })
        }
        |> Schema.describe "A shipment as first stored."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: ShipmentV1) : Result<ShipmentV1, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<ShipmentV1, SchemaErrors> =
        Schema.parse schema input

[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module DeliveryMethod =

    open Reified.SchemaDSL

    let private cases =
        [ UnionCase.fields "pickup" DeliveryMethod.Pickup (function DeliveryMethod.Pickup payload -> Some payload | _ -> None) PickupPoint.schema
          UnionCase.fields "courier" DeliveryMethod.Courier (function DeliveryMethod.Courier payload -> Some payload | _ -> None) CourierDelivery.schema ]

    let schema : Schema<DeliveryMethod> =
        Schema.unionWith (UnionRepresentation.Internal "kind") cases

/// Schema and boundary functions for Shipment (shipment.fs, Shipment.v2).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Shipment =

    open Reified.SchemaDSL
    open Reified.ConstraintDSL

    let private priorityCases =
        [ EnumCase.create "standard" ShipmentPriority.Standard
          EnumCase.create "express" ShipmentPriority.Express
          EnumCase.create "same-day" ShipmentPriority.SameDay ]

    /// The schema declared by shipment.fs (Shipment.v2).
    let schema : Schema<Shipment> =
        schema<Shipment> {
            fieldAs "reference" (fun (value: Shipment) -> value.Reference) {
                withSchema (Schema.text |> Schema.describe "Public shipment reference.")
                constrain (pattern "^SH-[0-9]+$")
            }
            fieldAs "notify_email" (fun (value: Shipment) -> value.NotifyEmail) {
                constrain email
            }
            fieldAs "items" (fun (value: Shipment) -> value.Items) {
                withSchema (Schema.mapWith Schema.int)
            }
            fieldAs "tags" (fun (value: Shipment) -> value.Tags) {
                withSchema (Schema.listWith Schema.text)
                constraints [
                    minLength 1
                    Constraint.distinct
                ]
            }
            fieldAs "weightKg" (fun (value: Shipment) -> value.WeightKg) {
                constrain (atLeast 0.5m)
            }
            fieldAs "priority" (fun (value: Shipment) -> value.Priority) {
                withSchema (Schema.enum priorityCases |> Schema.withDefault ShipmentPriority.Express)
            }
            fieldAs "delivery" (fun (value: Shipment) -> value.Delivery) {
                withSchema DeliveryMethod.schema
            }
            fieldAs "origin" (fun (value: Shipment) -> value.Origin) {
                withSchema (Schema.option PickupPoint.schema)
            }
            fieldAs "boxes" (fun (value: Shipment) -> value.Boxes) {
                withSchema (Schema.int |> Schema.withDefault 1)
                constrain (atLeast 1)
            }
            construct (fun reference notifyEmail items tags weightKg priority delivery origin boxes ->
                { Shipment.Reference = reference
                  Shipment.NotifyEmail = notifyEmail
                  Shipment.Items = items
                  Shipment.Tags = tags
                  Shipment.WeightKg = weightKg
                  Shipment.Priority = priority
                  Shipment.Delivery = delivery
                  Shipment.Origin = origin
                  Shipment.Boxes = boxes })
        }
        |> Schema.describe "A shipment with delivery method, priority, and weight."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: Shipment) : Result<Shipment, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<Shipment, SchemaErrors> =
        Schema.parse schema input

    /// Builds the versioned wire contract; supply each n-1 -> n migration and the version-detection source.
    let contract
        (migrateV1ToV2: ShipmentV1 -> Result<Shipment, MigrationError>)
        (source: VersionSource)
        : Contract<Shipment> =
        Contract.create "Shipment" 2 schema
        |> Contract.supersedes 1 ShipmentV1.schema migrateV1ToV2
        |> Contract.build source
