// <auto-generated>
//   Generated by reified schemagen from shipment.fs (PickupPoint.v1, CourierDelivery.v1, Shipment.v1, Shipment.v2).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Reified.Tests.Generated

open Reified

/// Schema and boundary functions for PickupPoint (shipment.fs, PickupPoint.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module PickupPoint =

    open Reified.SchemaDSL
    open Reified.ConstraintDSL
    open type PickupPoint

    /// The schema declared by shipment.fs (PickupPoint.v1).
    let schema =
        schema<PickupPoint> {
            fieldAs "code" _.Code
            construct (fun code ->
                { Code = code })
        }
        |> Schema.describe "A named pickup location."

    /// Validates an ordinary record-literal draft of PickupPoint.
    let validate (draft: PickupPoint) : Result<PickupPoint, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data into PickupPoint.
    let parse (input: Data) : Result<PickupPoint, SchemaErrors> =
        Schema.parse schema input

/// Schema and boundary functions for CourierDelivery (shipment.fs, CourierDelivery.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module CourierDelivery =

    open Reified.SchemaDSL
    open Reified.ConstraintDSL
    open type CourierDelivery

    /// The schema declared by shipment.fs (CourierDelivery.v1).
    let schema =
        schema<CourierDelivery> {
            fieldAs "trackingUrl" _.TrackingUrl
            construct (fun trackingUrl ->
                { TrackingUrl = trackingUrl })
        }
        |> Schema.describe "A courier delivery with tracking."

    /// Validates an ordinary record-literal draft of CourierDelivery.
    let validate (draft: CourierDelivery) : Result<CourierDelivery, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data into CourierDelivery.
    let parse (input: Data) : Result<CourierDelivery, SchemaErrors> =
        Schema.parse schema input

/// Schema and boundary functions for ShipmentV1 (shipment.fs, Shipment.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module ShipmentV1 =

    open Reified.SchemaDSL
    open Reified.ConstraintDSL
    open type ShipmentV1

    /// The schema declared by shipment.fs (Shipment.v1).
    let schema =
        schema<ShipmentV1> {
            fieldAs "reference" _.Reference {
                withSchema (Schema.text |> Schema.describe "Public shipment reference.")
                constrain (pattern "^SH-[0-9]+$")
            }
            fieldAs "notifyEmail" _.NotifyEmail {
                constrain email
            }
            fieldAs "items" _.Items
            construct (fun reference notifyEmail items ->
                { Reference = reference
                  NotifyEmail = notifyEmail
                  Items = items })
        }
        |> Schema.describe "A shipment as first stored."

    /// Validates an ordinary record-literal draft of ShipmentV1.
    let validate (draft: ShipmentV1) : Result<ShipmentV1, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data into ShipmentV1.
    let parse (input: Data) : Result<ShipmentV1, SchemaErrors> =
        Schema.parse schema input

[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module DeliveryMethod =

    open Reified.SchemaDSL

    let private cases =
        [ UnionCase.fields "pickup" DeliveryMethod.Pickup (function DeliveryMethod.Pickup payload -> Some payload | _ -> None) PickupPoint.schema
          UnionCase.fields "courier" DeliveryMethod.Courier (function DeliveryMethod.Courier payload -> Some payload | _ -> None) CourierDelivery.schema ]

    let schema : Schema<DeliveryMethod> =
        Schema.unionWith (UnionRepresentation.Internal "kind") cases

/// Schema and boundary functions for Shipment (shipment.fs, Shipment.v2).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Shipment =

    open Reified.SchemaDSL
    open Reified.ConstraintDSL
    open type Shipment

    let private priorityCases =
        [ EnumCase.create "standard" ShipmentPriority.Standard
          EnumCase.create "express" ShipmentPriority.Express
          EnumCase.create "same-day" ShipmentPriority.SameDay ]

    /// The schema declared by shipment.fs (Shipment.v2).
    let schema =
        schema<Shipment> {
            fieldAs "reference" _.Reference {
                withSchema (Schema.text |> Schema.describe "Public shipment reference.")
                constrain (pattern "^SH-[0-9]+$")
            }
            fieldAs "notify_email" _.NotifyEmail {
                constrain email
            }
            fieldAs "items" _.Items
            fieldAs "tags" _.Tags {
                constraints [
                    minLength 1
                    Constraint.distinct
                ]
            }
            fieldAs "weightKg" _.WeightKg {
                constrain (atLeast 0.5m)
            }
            fieldAs "priority" _.Priority {
                withSchema (Schema.enum priorityCases |> Schema.withDefault ShipmentPriority.Express)
            }
            fieldAs "delivery" _.Delivery {
                withSchema DeliveryMethod.schema
            }
            fieldAs "origin" _.Origin {
                withSchema (Schema.option PickupPoint.schema)
            }
            fieldAs "boxes" _.Boxes {
                withSchema (Schema.int |> Schema.withDefault 1)
                constrain (atLeast 1)
            }
            construct (fun reference notifyEmail items tags weightKg priority delivery origin boxes ->
                { Reference = reference
                  NotifyEmail = notifyEmail
                  Items = items
                  Tags = tags
                  WeightKg = weightKg
                  Priority = priority
                  Delivery = delivery
                  Origin = origin
                  Boxes = boxes })
        }
        |> Schema.describe "A shipment with delivery method, priority, and weight."

    /// Validates an ordinary record-literal draft of Shipment.
    let validate (draft: Shipment) : Result<Shipment, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data into Shipment.
    let parse (input: Data) : Result<Shipment, SchemaErrors> =
        Schema.parse schema input

    /// Builds the versioned wire contract; supply each n-1 -> n migration and the version-detection source.
    let contract
        (migrateV1ToV2: ShipmentV1 -> Result<Shipment, MigrationError>)
        (source: VersionSource)
        : Contract<Shipment> =
        Contract.create "Shipment" 2 schema
        |> Contract.supersedes 1 ShipmentV1.schema migrateV1ToV2
        |> Contract.build source
