// <auto-generated>
//   Generated by reified schemagen from signup.contract (Signup.v1).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Reified.Tests.Generated

open Reified

/// The "plan" cases of Signup (signup.contract, Signup.v1).
[<RequireQualifiedAccess>]
type SignupPlan =
    | Free
    | Pro

/// A new account request.
type Signup =
    {
        /// Primary contact address.
        Email: string
        DisplayName: string option
        Age: int
        Plan: SignupPlan
        Tags: string list
        Limits: Map<string, int>
        Location: Geo option
    }

/// Schema and boundary functions for Signup (signup.contract, Signup.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module Signup =

    open Reified.SchemaDSL
    open Reified.ConstraintDSL
    open type Signup

    let private planCases =
        [ EnumCase.create "free" SignupPlan.Free
          EnumCase.create "pro" SignupPlan.Pro ]

    /// The schema declared by signup.contract (Signup.v1).
    let schema =
        schema<Signup> {
            fieldAs "email" _.Email {
                withSchema (Schema.text |> Schema.describe "Primary contact address.")
                constraints [
                    email
                    maxLength 254
                ]
            }
            fieldAs "display_name" _.DisplayName {
                withSchema (Schema.option (Schema.text |> Schema.constrainAll [ Constraint.minLength (1); Constraint.maxLength (64) ]))
            }
            fieldAs "age" _.Age {
                constrain (atLeast 13)
            }
            fieldAs "plan" _.Plan {
                withSchema (Schema.enum planCases |> Schema.withDefault SignupPlan.Free)
            }
            fieldAs "tags" _.Tags {
                constraints [
                    maxLength 8
                    Constraint.distinct
                ]
            }
            fieldAs "limits" _.Limits
            fieldAs "location" _.Location {
                withSchema (Schema.option Geo.schema)
            }
            construct (fun email displayName age plan tags limits location ->
                { Email = email
                  DisplayName = displayName
                  Age = age
                  Plan = plan
                  Tags = tags
                  Limits = limits
                  Location = location })
        }
        |> Schema.describe "A new account request."

    /// Validates an ordinary record-literal draft of Signup.
    let validate (draft: Signup) : Result<Signup, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data into Signup.
    let parse (input: Data) : Result<Signup, SchemaErrors> =
        Schema.parse schema input
