// <auto-generated>
//   Generated by reified schemagen from union-compat.fs (UnionCompatibilityEnvelope.v1).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Reified.Tests.Generated

open Reified
open Reified.SchemaDSL

[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module WorkflowId =

    type private Model = WorkflowId
    let schema = Schema.convert Model.WorkflowId (function Model.WorkflowId value -> value) Schema.text

[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module RecommendedCommand =

    type private Model = RecommendedCommand
    open type Model

    type private MoveCasePayload = {
        x: int
        y: int
    }

    let private tryMoveCase = function
        | Move(x, y) -> Some { x = x; y = y }
        | _ -> None

    let schema =
        Schema.union [
            UnionCase.empty "stop" Stop (function Stop -> true | _ -> false)
            case "move" {
                tryExtract tryMoveCase
                fieldAs "x" _.x
                fieldAs "y" _.y
                construct (fun x y -> Move(x, y))
            }
        ]

[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module FSharpSystemTextJsonCommand =

    type private Model = FSharpSystemTextJsonCommand
    open type Model

    let private tryScaleCase = function
        | Scale amount -> Some amount
        | _ -> None

    type private TranslateCasePayload = {
        x: int
        y: int
    }

    let private tryTranslateCase = function
        | Translate(x, y) -> Some { x = x; y = y }
        | _ -> None

    let schema =
        Schema.unionWith (UnionRepresentation.Adjacent("Case", "Fields", UnionPayloadStyle.Positional)) [
            UnionCase.empty "Pause" Pause (function Pause -> true | _ -> false)
            case "Scale" {
                tryExtract tryScaleCase
                fieldAs "amount" id
                construct Scale
            }
            case "Translate" {
                tryExtract tryTranslateCase
                fieldAs "x" _.x
                fieldAs "y" _.y
                construct (fun x y -> Translate(x, y))
            }
        ]

[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module CompactExternalCommand =

    type private Model = CompactExternalCommand
    open type Model

    let private tryRenameCase = function
        | Rename name -> Some name
        | _ -> None

    type private ResizeCasePayload = {
        width: int
        height: int
    }

    let private tryResizeCase = function
        | Resize(width, height) -> Some { width = width; height = height }
        | _ -> None

    let schema =
        Schema.unionWith (UnionRepresentation.External(UnionPayloadStyle.NamedWithUnwrappedSingle, true)) [
            UnionCase.empty "cancel" Cancel (function Cancel -> true | _ -> false)
            case "rename" {
                tryExtract tryRenameCase
                fieldAs "name" id
                construct Rename
            }
            case "resize" {
                tryExtract tryResizeCase
                fieldAs "width" _.width
                fieldAs "height" _.height
                construct (fun width height -> Resize(width, height))
            }
        ]

/// Schema for UnionCompatibilityEnvelope.
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module UnionCompatibilityEnvelope =

    type private Model = UnionCompatibilityEnvelope
    open type Model

    let schema =
        schema<Model> {
            fieldAs "workflowId" _.WorkflowId {
                withSchema WorkflowId.schema
            }
            fieldAs "recommended" _.Recommended {
                withSchema RecommendedCommand.schema
            }
            fieldAs "fSharpSystemTextJson" _.FSharpSystemTextJson {
                withSchema FSharpSystemTextJsonCommand.schema
            }
            fieldAs "compactExternal" _.CompactExternal {
                withSchema CompactExternalCommand.schema
            }
            construct (fun workflowId recommended fSharpSystemTextJson compactExternal ->
                { WorkflowId = workflowId
                  Recommended = recommended
                  FSharpSystemTextJson = fSharpSystemTextJson
                  CompactExternal = compactExternal })
        }

    let validate = Schema.check schema
    let parse = Schema.parse schema
