// <auto-generated>
//   Generated by reified schemagen from union-compat.fs (UnionCompatibilityEnvelope.v1).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Reified.Tests.Generated

open Reified

[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module RecommendedCommand =

    open Reified.SchemaDSL

    type private MoveCasePayload = {
        x: int
        y: int
    }

    let private moveCasePayload =
        schema<MoveCasePayload> {
            fieldAs "x" _.x
            fieldAs "y" _.y
            construct (fun x y -> { x = x; y = y })
        }

    let private cases =
        [ UnionCase.empty "stop" RecommendedCommand.Stop (function RecommendedCommand.Stop -> true | _ -> false)
          UnionCase.fields "move" (fun (payload: MoveCasePayload) -> RecommendedCommand.Move(payload.x, payload.y)) (function RecommendedCommand.Move(x, y) -> Some { x = x; y = y } | _ -> None) moveCasePayload ]

    let schema : Schema<RecommendedCommand> =
        Schema.unionWith (UnionRepresentation.Internal "type") cases

[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module FSharpSystemTextJsonCommand =

    open Reified.SchemaDSL

    type private ScaleCasePayload = { amount: decimal }

    let private scaleCasePayload =
        schema<ScaleCasePayload> {
            fieldAs "amount" _.amount
            construct (fun amount -> { amount = amount })
        }

    type private TranslateCasePayload = {
        x: int
        y: int
    }

    let private translateCasePayload =
        schema<TranslateCasePayload> {
            fieldAs "x" _.x
            fieldAs "y" _.y
            construct (fun x y -> { x = x; y = y })
        }

    let private cases =
        [ UnionCase.empty "Pause" FSharpSystemTextJsonCommand.Pause (function FSharpSystemTextJsonCommand.Pause -> true | _ -> false)
          UnionCase.fields "Scale" (fun (payload: ScaleCasePayload) -> FSharpSystemTextJsonCommand.Scale(payload.amount)) (function FSharpSystemTextJsonCommand.Scale(amount) -> Some { amount = amount } | _ -> None) scaleCasePayload
          UnionCase.fields "Translate" (fun (payload: TranslateCasePayload) -> FSharpSystemTextJsonCommand.Translate(payload.x, payload.y)) (function FSharpSystemTextJsonCommand.Translate(x, y) -> Some { x = x; y = y } | _ -> None) translateCasePayload ]

    let schema : Schema<FSharpSystemTextJsonCommand> =
        Schema.unionWith (UnionRepresentation.Adjacent("Case", "Fields", UnionPayloadStyle.Positional)) cases

[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module CompactExternalCommand =

    open Reified.SchemaDSL

    type private RenameCasePayload = { name: string }

    let private renameCasePayload =
        schema<RenameCasePayload> {
            fieldAs "name" _.name
            construct (fun name -> { name = name })
        }

    type private ResizeCasePayload = {
        width: int
        height: int
    }

    let private resizeCasePayload =
        schema<ResizeCasePayload> {
            fieldAs "width" _.width
            fieldAs "height" _.height
            construct (fun width height -> { width = width; height = height })
        }

    let private cases =
        [ UnionCase.empty "cancel" CompactExternalCommand.Cancel (function CompactExternalCommand.Cancel -> true | _ -> false)
          UnionCase.fields "rename" (fun (payload: RenameCasePayload) -> CompactExternalCommand.Rename(payload.name)) (function CompactExternalCommand.Rename(name) -> Some { name = name } | _ -> None) renameCasePayload
          UnionCase.fields "resize" (fun (payload: ResizeCasePayload) -> CompactExternalCommand.Resize(payload.width, payload.height)) (function CompactExternalCommand.Resize(width, height) -> Some { width = width; height = height } | _ -> None) resizeCasePayload ]

    let schema : Schema<CompactExternalCommand> =
        Schema.unionWith (UnionRepresentation.External(UnionPayloadStyle.NamedWithUnwrappedSingle, true)) cases

/// Schema and boundary functions for UnionCompatibilityEnvelope (union-compat.fs, UnionCompatibilityEnvelope.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module UnionCompatibilityEnvelope =

    open Reified.SchemaDSL
    open Reified.ConstraintDSL
    open type UnionCompatibilityEnvelope

    /// The schema declared by union-compat.fs (UnionCompatibilityEnvelope.v1).
    let schema =
        schema<UnionCompatibilityEnvelope> {
            fieldAs "workflowId" _.WorkflowId {
                withSchema (Schema.convert WorkflowId (function WorkflowId value -> value) Schema.text)
            }
            fieldAs "recommended" _.Recommended {
                withSchema RecommendedCommand.schema
            }
            fieldAs "fSharpSystemTextJson" _.FSharpSystemTextJson {
                withSchema FSharpSystemTextJsonCommand.schema
            }
            fieldAs "compactExternal" _.CompactExternal {
                withSchema CompactExternalCommand.schema
            }
            construct (fun workflowId recommended fSharpSystemTextJson compactExternal ->
                { WorkflowId = workflowId
                  Recommended = recommended
                  FSharpSystemTextJson = fSharpSystemTextJson
                  CompactExternal = compactExternal })
        }

    /// Validates an ordinary record-literal draft of UnionCompatibilityEnvelope.
    let validate (draft: UnionCompatibilityEnvelope) : Result<UnionCompatibilityEnvelope, SchemaErrors> =
        Schema.check schema draft

    /// Parses structured boundary data into UnionCompatibilityEnvelope.
    let parse (input: Data) : Result<UnionCompatibilityEnvelope, SchemaErrors> =
        Schema.parse schema input
