// <auto-generated>
//   Generated by axial schemagen from workspace.fs (WorkspaceCard.v1, WorkspaceCard.v2).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Axial.ReferenceApp.Wire

open Axial
open Axial.Validation
open Axial.Schema

/// Schema and boundary functions for WorkspaceCardV1 (workspace.fs, WorkspaceCard.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module WorkspaceCardV1 =

    open Axial.Schema.Syntax

    /// The schema declared by workspace.fs (WorkspaceCard.v1).
    let schema : Schema<WorkspaceCardV1> =
        Schema.define<WorkspaceCardV1>
        |> fieldWith (Schema.text |> Schema.describe "Display name of the workspace.") "name" _.Name
        |> constrain (minLength 1)
        |> constrain (maxLength 60)
        |> field "owner" _.Owner
        |> construct (fun name owner ->
            { Name = name
              Owner = owner })
        |> Schema.describe "A workspace card as first exported: one owner string of the form \"Name <email>\"."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: WorkspaceCardV1) : Result<WorkspaceCardV1, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<WorkspaceCardV1, Diagnostics<SchemaError>> =
        Schema.parse schema input

    /// Typed field references for rules, redisplay, and UI binding.
    [<RequireQualifiedAccess>]
    module Fields =
        let name : FieldRef<WorkspaceCardV1, string> = { Name = "name"; Get = _.Name; Set = fun draft value -> { draft with Name = value } }
        let owner : FieldRef<WorkspaceCardV1, string> = { Name = "owner"; Get = _.Owner; Set = fun draft value -> { draft with Owner = value } }

/// Schema and boundary functions for WorkspaceCard (workspace.fs, WorkspaceCard.v2).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module WorkspaceCard =

    open Axial.Schema.Syntax

    let private visibilityCases =
        [ EnumCase.create "private" Visibility.Private
          EnumCase.create "team" Visibility.Team
          EnumCase.create "org-wide" Visibility.OrgWide ]

    /// The schema declared by workspace.fs (WorkspaceCard.v2).
    let schema : Schema<WorkspaceCard> =
        Schema.define<WorkspaceCard>
        |> fieldWith (Schema.text |> Schema.describe "Display name of the workspace.") "name" _.Name
        |> constrain (minLength 1)
        |> constrain (maxLength 60)
        |> field "owner_email" _.OwnerEmail
        |> constrain emailFormat
        |> fieldWith (Schema.enum visibilityCases |> Schema.withDefault Visibility.Private) "visibility" _.Visibility
        |> field "members" _.Members
        |> constrain distinct
        |> construct (fun name ownerEmail visibility members -> WorkspaceCard.create name ownerEmail visibility members)
        |> Schema.describe "A workspace card with a dedicated owner email, visibility, and member emails."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: WorkspaceCard) : Result<WorkspaceCard, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<WorkspaceCard, Diagnostics<SchemaError>> =
        Schema.parse schema input

    /// Builds the versioned wire contract; supply each n-1 -> n migration and the version-detection source.
    let contract
        (migrateV1ToV2: WorkspaceCardV1 -> Result<WorkspaceCard, MigrationError>)
        (source: VersionSource)
        : Contract<WorkspaceCard> =
        Contract.create "WorkspaceCard" 2 schema
        |> Contract.supersedes 1 WorkspaceCardV1.schema migrateV1ToV2
        |> Contract.build source

    /// Typed field references for rules, redisplay, and UI binding.
    [<RequireQualifiedAccess>]
    module Fields =
        let name : FieldRef<WorkspaceCard, string> = { Name = "name"; Get = _.Name; Set = fun draft value -> { draft with Name = value } }
        let ownerEmail : FieldRef<WorkspaceCard, string> = { Name = "owner_email"; Get = _.OwnerEmail; Set = fun draft value -> { draft with OwnerEmail = value } }
        let visibility : FieldRef<WorkspaceCard, Visibility> = { Name = "visibility"; Get = _.Visibility; Set = fun draft value -> { draft with Visibility = value } }
        let members : FieldRef<WorkspaceCard, string list> = { Name = "members"; Get = _.Members; Set = fun draft value -> { draft with Members = value } }
