// <auto-generated>
//   Generated by axial schemagen from workspace.fs (WorkspaceCard.v1, WorkspaceCard.v2).
//   Do not edit directly; edit the contract source and regenerate.
// </auto-generated>
namespace Axial.ReferenceApp.Wire

open Axial
open Axial.Validation
open Axial.Schema

/// Schema and boundary functions for WorkspaceCardV1 (workspace.fs, WorkspaceCard.v1).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module WorkspaceCardV1 =

    open Axial.Schema.Syntax

    /// The schema declared by workspace.fs (WorkspaceCard.v1).
    let schema : Schema<WorkspaceCardV1> =
        SchemaCE.schema<WorkspaceCardV1> {
            SchemaCE.field "name" (fun (value: WorkspaceCardV1) -> value.Name) {
                withSchema (Schema.text |> Schema.describe "Display name of the workspace.")
                constrain (minLength 1)
                constrain (maxLength 60)
            }
            SchemaCE.field "owner" (fun (value: WorkspaceCardV1) -> value.Owner)
            SchemaCE.construct (fun name owner ->
                { Name = name
                  Owner = owner })
        }
        |> Schema.describe "A workspace card as first exported: one owner string of the form \"Name <email>\"."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: WorkspaceCardV1) : Result<WorkspaceCardV1, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<WorkspaceCardV1, Diagnostics<SchemaError>> =
        Schema.parse schema input

/// Schema and boundary functions for WorkspaceCard (workspace.fs, WorkspaceCard.v2).
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>]
[<RequireQualifiedAccess>]
module WorkspaceCard =

    open Axial.Schema.Syntax

    let private visibilityCases =
        [ EnumCase.create "private" Visibility.Private
          EnumCase.create "team" Visibility.Team
          EnumCase.create "org-wide" Visibility.OrgWide ]

    /// The schema declared by workspace.fs (WorkspaceCard.v2).
    let schema : Schema<WorkspaceCard> =
        SchemaCE.schema<WorkspaceCard> {
            SchemaCE.field "name" (fun (value: WorkspaceCard) -> value.Name) {
                withSchema (Schema.text |> Schema.describe "Display name of the workspace.")
                constrain (minLength 1)
                constrain (maxLength 60)
            }
            SchemaCE.field "owner_email" (fun (value: WorkspaceCard) -> value.OwnerEmail) {
                constrain emailFormat
            }
            SchemaCE.field "visibility" (fun (value: WorkspaceCard) -> value.Visibility) {
                withSchema (Schema.enum visibilityCases |> Schema.withDefault Visibility.Private)
            }
            SchemaCE.field "members" (fun (value: WorkspaceCard) -> value.Members) {
                withSchema (Schema.listWith Schema.text)
                constrain distinct
            }
            SchemaCE.construct (fun name ownerEmail visibility members -> WorkspaceCard.create name ownerEmail visibility members)
        }
        |> Schema.describe "A workspace card with a dedicated owner email, visibility, and member emails."

    /// Checks a draft built with an ordinary record literal.
    let validate (draft: WorkspaceCard) : Result<WorkspaceCard, Diagnostics<SchemaError>> =
        Schema.check schema draft

    /// Parses structured boundary data through the schema.
    let parse (input: Data) : Result<WorkspaceCard, Diagnostics<SchemaError>> =
        Schema.parse schema input

    /// Builds the versioned wire contract; supply each n-1 -> n migration and the version-detection source.
    let contract
        (migrateV1ToV2: WorkspaceCardV1 -> Result<WorkspaceCard, MigrationError>)
        (source: VersionSource)
        : Contract<WorkspaceCard> =
        Contract.create "WorkspaceCard" 2 schema
        |> Contract.supersedes 1 WorkspaceCardV1.schema migrateV1ToV2
        |> Contract.build source
