// User-owned wire declarations. The sibling workspace.g.fs is generated by axial schemagen;
// regenerate it after editing this file (the build target does this when the tool is present).
namespace Axial.ReferenceApp.Wire

open Axial.Schema.Wire

/// Who can see a workspace card.
type Visibility =
    | Private
    | Team
    | [<WireName "org-wide">] OrgWide

/// A workspace card as first exported: one owner string of the form "Name <email>".
[<WireSchema>]
type WorkspaceCardV1 =
    { /// Display name of the workspace.
      [<Min 1; Max 60>]
      Name: string
      Owner: string }

/// A workspace card with a dedicated owner email, visibility, and member emails.
[<WireSchema>]
type WorkspaceCard =
    { /// Display name of the workspace.
      [<Min 1; Max 60>]
      Name: string
      [<Email; WireName "owner_email">]
      OwnerEmail: string
      [<Default "private">]
      Visibility: Visibility
      [<Distinct>]
      Members: string list }
