// User-owned wire declarations. The sibling workspace.g.fs is generated by axial schemagen;
// regenerate it after editing this file (the build target does this when the tool is present).
namespace Axial.ReferenceApp.Wire

open Axial.Schema.Derive

/// Who can see a workspace card.
type Visibility =
    | Private
    | Team
    | [<SchemaName "org-wide">] OrgWide

/// A workspace card as first exported: one owner string of the form "Name <email>".
[<DeriveSchema>]
type WorkspaceCardV1 =
    { /// Display name of the workspace.
      [<Min 1; Max 60>]
      Name: string
      Owner: string }

/// A workspace card with a dedicated owner email, visibility, and member emails.
[<DeriveSchema; SchemaConstructor "WorkspaceCard.create">]
type WorkspaceCard =
    { /// Display name of the workspace.
      [<Min 1; Max 60>]
      Name: string
      [<Email; SchemaName "owner_email">]
      OwnerEmail: string
      [<Default "private">]
      Visibility: Visibility
      [<Distinct>]
      Members: string list }

    /// Called by the generated schema instead of a record literal: normalises the owner email
    /// to lower case on the way in. Static member, not a module — the generated module already
    /// takes the record's name.
    static member create name (ownerEmail: string) visibility members =
        { Name = name
          OwnerEmail = ownerEmail.ToLowerInvariant()
          Visibility = visibility
          Members = members }
